### ISSUE TITLE
Where is secret.sh?

### ISSUE THREAD

**Issue by paradox1979** [charlielito/web-avatarify#3]
what is secret.sh, and where is it?

**Comment by charlielito** [comment]
It is gitignored. As the `Readme` says, you need to create that file defining some env variables.
My secrets.sh looks like this:
```bash
export API_TOKEN='xxxxxxxxxx'
export REACT_APP_API_TOKEN=$API_TOKEN
export SERVER_URL="xxxxxxxxx" #this is the IP address or the domain where your backend is
```

**Comment by paradox1979** [comment]
Thank you so much. I already generated JWT token, and appplyed to code.

Thanks kindly,

-Lucas


2020년 6월 18일 (목) 오전 10:51, Carlos Andrés Álvarez Restrepo <
notifications@github.com>님이 작성:
